[phases.setup]
nixPkgs = ['ffmpeg']

[phases.install]
cmds = [
  'rm -rf .venv',
  'pip install --upgrade pip setuptools wheel',
  'pip install -r requirements.txt --no-cache-dir --force-reinstall'
]

[start]
cmd = 'python bot_production.py'
